### ISSUE TITLE
no accepting test

### ISSUE THREAD

**Issue by MandyMeindersma** [CMPUT301F16T01/Carrier#174]
My branch (adding vehicle info with bennett) says there are no tests anywhere ever. PANIC

**Comment by Hreherch** [comment]
Is this because of a missing instrumentation runner?
Try this: https://google.github.io/android-testing-support-library/docs/espresso/setup/index.html#running-tests

You basically go into the drop down menu between the hammer and the play button, and there should be a "edit configuration" button. In there you should be able to select an test runner with the "..." beside the "specific instrumentation runner" text box.

**Comment by MandyMeindersma** [comment]
you fixed it! Thank you <3
