### ISSUE TITLE
User XML - Driver Searching

### ISSUE THREAD

**Issue by sehoven** [CMPUT301F16T01/Carrier#49]
- [ ] Search Requests page
- [ ] List of requests (what Mandy suggested below)

**Comment by MandyMeindersma** [comment]
Just to clarify: I am pretty sure you will have to do the XML where the user picks to choose by geolocation or by key word and then you will also have to show a list of all requests This will be 2 XML

**Comment by Hreherch** [comment]
There's potential to remove complexity, by adding a special keyword we could do a geolocation search, otherwise do a keyword search. 
Or for example, we could just bring up a list of requests by geolocation, and if they type in a search bar above the requests they can search by keyword. We can add a button beside the search bar that initiates the geolocation search. (I can probably draw this better in the meeting tomorrow)
